version: '2'

networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # environment:
    #   -  'MONGODB_USER=user' 
    #   -  'MONGODB_PASS=password!'
    # volumes:
    #   - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'

volumes:
  mongodb-data: {}